- defaults:
    link:
      relink: true

- clean: ['~']
- link:
    ~/.dotfiles: ''
    ~/.tmux.conf:
    ~/.vscodevimrc:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/.zimrc:
    ~/.zprofile:
- shell:
    - [git submodule update --init --recursive, Installing submodules]
