- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']
- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.tmux.conf:
    ~/.vscodevimrc:
    ~/.config/nvim:
    ~/.config/fish/config.fish: fish/config.fish
- shell:
    - [git submodule update --init --recursive, Installing submodules]
