- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']
- link:
    ~/.dotfiles: ''
    ~/.tmux.conf:
    ~/.vscodevimrc:
    ~/.vim:
    ~/.vimrc:
    # ~/.config/nvim: editor/config/nvim
    ~/.config/nvim: lazyvim
    ~/.config/fish/config.fish: fish/config.fish
- shell:
    - [git submodule update --init --recursive, Installing submodules]
