- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config', '~/.gemini']
- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.tmux.conf:
    ~/.vscodevimrc:
    ~/.config/nvim:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.gemini/GEMINI.md: agentic/AGENT.md
- shell:
    - [git submodule update --init --recursive, Installing submodules]
