- defaults:
    link:
      relink: true

- clean: ['~']
- link:
    ~/.tmux.conf:
    ~/.vscodevimrc:
    ~/.inputrc:
    ~/.vim:
    ~/.vimrc:
- shell:
    - [git submodule update --init --recursive, Installing submodules]
