- defaults:
    link:
      relink: true
      force: true

- clean: ['~']
- link:
    ~/.dotfiles: ''
    ~/.tmux.conf:
    ~/.vscodevimrc:
    ~/.vim:
    ~/.vimrc:
    ~/.config/fish/config.fish: fish/config.fish
- shell:
    - [git submodule update --init --recursive, Installing submodules]
